### ISSUE TITLE
图片很多的时候如何像ScrollView可上下滑动

### ISSUE THREAD

**Issue by Brokenwind** [albert-lii/AutoGridView#1]
你的AutoGridView不支持上下滑动，当我有很多图片的时候，我在外层加了一个ScrollView，但是显示大图浏览模式有问题，会只在屏幕的最上边一小块显示。
<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.liyi.grid.AutoGridView
            android:id="@+id/autoGridView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:grid_column="3" />

        <com.liyi.viewer.widget.ImageViewer
            android:id="@+id/imagePreivew"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </RelativeLayout>
</ScrollView>

**Comment by albert-lii** [comment]
你把<RelativeLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content">的   android:layout_height="wrap_content"换成match_height

**Comment by albert-lii** [comment]
1、AutoGridView主要是针对类似QQ空间以及朋友圈那种九宫格图片展示的，如果网格图片很多，建议直接使用gridview或者recyclerview
2、AutoGridView会根据你的item个数来自动获取到所需要的高度，所以设置高度为wrap_content没有问题，但是ImageViewer不会，需要你手动设置高度，一般建议全屏
