### ISSUE TITLE
AutoGridView 作为RecyclerView的Item数据无法显示

### ISSUE THREAD

**Issue by FY6** [albert-lii/AutoGridView#2]
AutoGridView 作为RecyclerView的Item数据无法显示
mGridAdp.data = item.mImages
helper.itemView.mAutoGridView.setAdapter(mGridAdp)

**Comment by albert-lii** [comment]
你好，

已经上传 AutoGridView 作为 RecyclerView 的 item 的例子！
你可以检查一下，在原来代码中是否在适配器中设置了 ImageLoader ！
如有疑问，欢迎 issue！
